version: '3.7'
services:
  solution:
    # Собираем контейнер с приложением с помощью uwsgi.Dockerfile
    # Присваеваем имя контейнера "flask_app"

    # ******** НИЖЕ НАПИШИТЕ КОД ВЫПОЛНЯЮЩИЙ 2 ДЕЙСТВИЯ ОПИСАННЫЕ ВЫШЕ
    build:
      context: ./app
      dockerfile: uwsgi.Dockerfile
    container_name: solution


  nginx_server:
    # Собираем контейнер с приложением с помощью /nginx/Dockerfile
    # Открываем 8000 порт для внешнего мира
    # Присваеваем имя контейнера "nginx_server"

    # ******** НИЖЕ НАПИШИТЕ КОД ВЫПОЛНЯЮЩИЙ 3 ДЕЙСТВИЯ ОПИСАННЫЕ ВЫШЕ
    build:
      context: ./nginx
    ports:
      - 5000:5000
    container_name: nginx_server
    restart: always
    depends_on:
      - solution


  checker:
    image: mike0sv/sf_docker_check
    container_name: checker
    restart: always
    depends_on:
      - solution
      - nginx_server


# 1. Перейти в директорию, содержащию поддиректорию app
# 2. Start the docker-compose
# sudo docker-compose up --build


